language: android
android:
  components:
    - build-tools-26.0.2
  licenses:
    - android-sdk-license-bcbbd656
    - '.*intel.+'
env:
  matrix:
    - ANDROID_SDKS=android-25,sysimg-25  ANDROID_TARGET=android-25
before_install:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET
  - emulator -avd test -no-skin -no-audio -no-window &
before_script:
  - chmod a+x ./ci/wait_for_emulator
  - ./ci/wait_for_emulator
  - adb shell input keyevent 82 &
